services:
################### DATABASES #############################################
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
     container_name: discountdb
     image: postgres
     restart: always
     environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin1234
        POSTGRES_DB: Discountdb
     ports:
        - "5432:5432"
     volumes:
        - postgres_data:/var/lib/postgresql/data/
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aspnetrun.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - discountdb
################### APPLICATION #############################################
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8080"
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
        - basketdb
    ports:
      - "8080"


  discount.api:
    container_name: discount.api
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=Discountdb;Username=admin;Password=admin1234
    ports:
      - "8080"


  discount.grpc:
    container_name: discount.grpc
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=Discountdb;Username=admin;Password=admin1234
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
